#!/usr/bin/env bash
# Install proxy-extract into an environment somebody else built - the FastVideo
# official Docker image - without moving a single package it already carries.
#
#   scripts/setup_docker_env.sh                 # the pipeline only
#   scripts/setup_docker_env.sh --with-flicker  # also moge3 + sam2
#   DRY_RUN=1 scripts/setup_docker_env.sh       # print the plan, install nothing
#
# Why this exists beside setup_venv.sh, which already installs this pipeline:
# that script builds an isolated venv from ../requirements.txt, and that file
# pins torch==2.13.0. This image is built around torch 2.12.0, and its
# flash-attn wheel is compiled against exactly that (`cu130torch2.12`), so
# swapping the torch would break the image's own training path. The driver is
# not ours to change either. And it would buy nothing: 2.12 runs this pipeline
# fine - `torch>=2.4` is all the backends ask for.
#
# So the rule here is: install only what is missing, and write everything the
# image does provide into a constraints file that the resolver is forbidden to
# move. A dependency that demands a different torch then fails loudly at install
# time instead of quietly upgrading one and surfacing days later as a node that
# cannot train.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

die() { echo "error: $*" >&2; exit 1; }
say() { printf '\n=== %s ===\n' "$*"; }

WITH_FLICKER=0
for arg in "$@"; do
  case "$arg" in
    --with-flicker) WITH_FLICKER=1 ;;
    -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
    *) die "unknown argument '$arg' (try --help)" ;;
  esac
done

# --------------------------------------------------------------- the environment

# $VIRTUAL_ENV when the image's activate has run, which its .bashrc/.zshrc does;
# /opt/venv is where the Dockerfile puts it, as the fallback for a login shell
# that skipped the rc file.
VENV="${VENV:-${VIRTUAL_ENV:-/opt/venv}}"
py="$VENV/bin/python"
[[ -x "$py" ]] || die "no python at $py. Set VENV=/path/to/venv, or run \
scripts/setup_venv.sh instead to build an isolated one from our own pins."

# uv is the image's own installer and is enormously faster on a tree this size.
# Plain pip is a correct fallback; both honour -c the same way.
if [[ -z "${PIP:-}" ]]; then
  if "$py" -m uv --version >/dev/null 2>&1; then
    PIP="$py -m uv pip"
  elif command -v uv >/dev/null 2>&1; then
    PIP="uv pip --python $py"
  else
    PIP="$py -m pip"
  fi
fi

say "environment"
echo "venv      $VENV"
echo "python    $("$py" --version 2>&1)"
echo "installer $PIP"

"$py" - <<'PY' || die "this python is older than proxy-extract's floor of 3.10"
import sys
raise SystemExit(0 if sys.version_info >= (3, 10) else 1)
PY

# ------------------------------------------------------------ what is already here

# Recorded before anything is installed so the check at the end can prove the
# install did not move them. torch is the one that matters; the rest are here
# because a resolver reaching for any of them tends to drag torch along.
PROTECTED=(
  torch torchvision torchaudio
  transformers tokenizers accelerate diffusers
  numpy flash-attn flashinfer-python
)

constraints="$(mktemp -t proxy-extract-constraints.XXXXXX)"
trap 'rm -f "$constraints"' EXIT

say "pinning what the image provides"
"$py" - "$constraints" "${PROTECTED[@]}" <<'PY'
import sys
from importlib.metadata import PackageNotFoundError, version

out, names = sys.argv[1], sys.argv[2:]
lines, absent = [], []
for name in names:
    try:
        lines.append(f"{name}=={version(name)}")
    except PackageNotFoundError:
        absent.append(name)

with open(out, "w") as handle:
    handle.write(
        "# Generated by scripts/setup_docker_env.sh from the live environment.\n"
        "# Not a preference - a fence. pip is to fail rather than move these.\n"
    )
    handle.write("\n".join(lines) + "\n")

for line in lines:
    print(f"  {line}")
if absent:
    print(f"  (absent, nothing to protect: {', '.join(absent)})")
PY

torch_before="$("$py" -c 'import torch; print(torch.__version__)' 2>/dev/null || echo none)"
[[ "$torch_before" == none ]] && die "this environment has no torch, so there is \
nothing to reuse. Use scripts/setup_venv.sh, which builds one from our pins."

# proxy-extract's own four runtime dependencies. Checked by import rather than by
# distribution name on purpose: the image ships `opencv-python` where our
# pyproject asks for `opencv-python-headless`, and those are two distributions
# providing the same `cv2`. Installing ours alongside theirs puts two copies of
# the module in one environment, which is a genuinely confusing failure - so the
# question to ask is "can I import cv2", not "is the headless wheel present".
say "checking proxy-extract's runtime dependencies"
"$py" - <<'PY' || die "a core dependency is missing; install the named ones and re-run"
import importlib
import sys

wanted = {
    "numpy": "numpy",
    "PIL": "pillow",
    "cv2": "opencv-python-headless  (the image's opencv-python also provides this)",
    "imageio_ffmpeg": "imageio-ffmpeg",
}
missing = []
for module, package in wanted.items():
    try:
        importlib.import_module(module)
        print(f"  ok      {module}")
    except ImportError:
        print(f"  MISSING {module}  -> pip install '{package}'")
        missing.append(package)
raise SystemExit(1 if missing else 0)
PY

# ------------------------------------------------------------------------ install

run() {
  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    echo "  would run: $*"
  else
    "$@"
  fi
}

say "installing proxy-extract (--no-deps)"
# --no-deps because every dependency was just confirmed present. Without it pip
# would fetch opencv-python-headless to satisfy the pyproject literally, and
# land a second cv2 next to the image's.
run $PIP install --no-deps -e "$here/proxy-extract"

if ((WITH_FLICKER)); then
  say "installing the anti-flicker backends under constraint"
  # Both are git-only. They are installed *with* their dependencies, unlike
  # DA3 elsewhere in this repo, because -c is the better tool: the resolver
  # still works out what they need, but cannot move anything in the fence. If
  # one of them genuinely requires a different torch, that is something to find
  # out now, from pip, rather than after a shard has been running for an hour.
  run $PIP install -c "$constraints" \
    "git+https://github.com/facebookresearch/sam2.git"
  run $PIP install -c "$constraints" \
    "git+https://github.com/microsoft/MoGe.git"
fi

# ------------------------------------------------------------------------- verify

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  say "dry run: nothing was installed"
  exit 0
fi

say "verifying the install moved nothing"
torch_after="$("$py" -c 'import torch; print(torch.__version__)')"
echo "torch before  $torch_before"
echo "torch after   $torch_after"
if [[ "$torch_before" != "$torch_after" ]]; then
  die "torch moved from $torch_before to $torch_after. That is the one thing this
       script exists to prevent, and the image's flash-attn wheel is built
       against the old one. Reinstall it:
         $PIP install --reinstall 'torch==$torch_before'"
fi

"$py" - <<'PY'
import shutil

import proxy_extract
from proxy_extract.proxy import EncodeError, ffmpeg_binary

print(f"proxy_extract   {proxy_extract.__file__}")
try:
    print(f"ffmpeg          {ffmpeg_binary()}")
except EncodeError as error:
    print(f"ffmpeg          MISSING\n{error}")

import torch

print(f"torch           {torch.__version__} (cuda {torch.version.cuda})")
available = torch.cuda.is_available()
print(f"cuda available  {available} ({torch.cuda.device_count() if available else 0} device(s))")
if not available and shutil.which("nvidia-smi"):
    print(
        "\nwarning: nvidia-smi is here but torch cannot use the GPUs. Inside this\n"
        "image that is a driver/CUDA mismatch rather than a wheel to swap - the\n"
        f"image is built for CUDA {torch.version.cuda}, so the host driver has to be new\n"
        "enough for it. Do not 'fix' this by installing another torch."
    )

for name, backend in (("moge3", "moge"), ("sam2", "sam2")):
    try:
        __import__(backend)
        print(f"{name:15} available")
    except ImportError:
        print(f"{name:15} not installed (re-run with --with-flicker)")
PY

say "self-check"
# The suite is the fastest way to find out whether this environment's numpy,
# opencv and pillow actually agree with the pipeline, and it needs no GPU. It is
# a gate rather than a report because the failures it catches here are the kind
# that produce valid-looking output - and SKIP_TESTS exists because being unable
# to start a run at all is the worse failure of the two.
if [[ "${SKIP_TESTS:-0}" == "1" ]]; then
  echo "skipped (SKIP_TESTS=1). Run it before trusting any output:"
  echo "  $py -m pytest $here/proxy-extract/tests -q"
else
  "$py" -m pytest "$here/proxy-extract/tests" -q || die "the test suite does not pass here.
       Do not start a run on this node yet. If the failures are all in
       test_depth_anything_v3.py the cause is a missing torch, which should be
       impossible in this image. Re-run with SKIP_TESTS=1 to proceed anyway."
fi

cat <<EOF

done. Nothing outside $VENV was touched, and torch is still $torch_after.

Next, in order:
  $py scripts/doctor.py                 # expect pin warnings; see RUNBOOK_DOCKER.md
  $py scripts/fetch_models.py --set flicker
  RUNBOOK_DOCKER.md                     # the two-node run
EOF
